# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

steps:
#  - task: DotNetCoreInstaller@0
#    inputs:
#      version: '2.2.401'
  - script: dotnet restore
  - script: dotnet build
  - script: dotnet publish -c Release -r linux-x64 -o cassie-linux-x64 --self-contained true
    